# Generated by Django 4.2.16 on 2024-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="background",
            field=models.TextField(blank=True, null=True),
        ),
    ]
