# Generated by Django 4.2.16 on 2024-11-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaign_background"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("channel", models.CharField(max_length=50)),
                ("schedule_date", models.DateField()),
                ("schedule_time", models.TimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_promo",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="CampaignChannel",),
    ]
