# Generated by Django 4.2.16 on 2024-11-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_campaignpromo_delete_campaignchannel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("discount", "Discount Pricing"),
                    ("code", "Promo Code"),
                    ("educational", "Educational"),
                    ("brand", "Brand"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="campaignpromo",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("fb", "Facebook"),
                    ("insta", "Instergram"),
                    ("tiktok", "TikTok"),
                    ("youtube", "Youtube"),
                    ("website", "Website"),
                    ("forum", "Forum(R2R)"),
                ],
                max_length=50,
            ),
        ),
    ]
