# Generated by Django 4.2.16 on 2024-11-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_alter_campaignpromo_schedule_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="campaignpromo", name="schedule_time",),
    ]
