# Generated by Django 5.1.2 on 2024-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_length_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
