# Generated by Django 5.1.2 on 2024-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "vendor_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Vendor ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Vendor Name")),
                (
                    "etf_vendor_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="ETF Vendor Code",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("inactive", "Temporarily Inactive"),
                            ("pending", "Pending"),
                        ],
                        max_length=20,
                        verbose_name="Vendor Status",
                    ),
                ),
            ],
        ),
    ]
