# Generated by Django 5.1.2 on 2024-11-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="id",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_id",
            field=models.CharField(
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Vendor ID",
            ),
        ),
    ]
